version: "3.9"

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin_pass_123
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      # nur lokal erreichbar (sicherer für Entwicklung)
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
